//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabBimestral.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Dependente = new HashSet<Dependente>();
        }
    
        public int ClienteID { get; set; }
        public string Nome { get; set; }
        public int TipoLogradouro { get; set; }
        public string Logradouro { get; set; }
        public int Bairro { get; set; }
        public int Cidade { get; set; }
        public string UF { get; set; }
        public long Telefone { get; set; }
        public long CPF { get; set; }
        public Nullable<long> RG { get; set; }
    
        public virtual Tipo_Logradouro Tipo_Logradouro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dependente> Dependente { get; set; }
    }
}
