//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabBimestral.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependente
    {
        public int DependenteID { get; set; }
        public int Cliente { get; set; }
        public string Nome { get; set; }
        public int TipoDependente { get; set; }
    
        public virtual TipoDependente TipoDependente1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
    }
}
