//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabBimestral.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BimestralTrabEntities : DbContext
    {
        public BimestralTrabEntities()
            : base("name=BimestralTrabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Dependente> Dependente { get; set; }
        public virtual DbSet<Tipo_Logradouro> Tipo_Logradouro { get; set; }
        public virtual DbSet<TipoDependente> TipoDependente { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    }
}
